version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.tika:tika-core
    versions:
    - "1.22"
  - dependency-name: org.apache.tomcat:tomcat-servlet-api
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
